"""Create func table

Revision ID: 8ab73c97f2ea
Revises: 7d8c445600a1
Create Date: 2025-09-12 20:11:10.774787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ab73c97f2ea'
down_revision: Union[str, Sequence[str], None] = '7d8c445600a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('functions', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('functions', 'name')
    # ### end Alembic commands ###
