"""Create functions table

Revision ID: e65fb710ba1d
Revises: faa47022df4e
Create Date: 2025-09-12 19:45:17.970221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e65fb710ba1d'
down_revision: Union[str, Sequence[str], None] = 'faa47022df4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('functions',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('type', sa.Enum('FUNCTION', 'IMAGE', name='functiontype'), nullable=False),
    sa.Column('source', sa.Enum('GITHUB', 'STORAGE', name='sourcetype'), nullable=False),
    sa.Column('location_url', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'DEPLOYED', name='statustype'), nullable=False),
    sa.Column('event_type', sa.Enum('HTTP', 'QUEUE_EVENT', name='eventtype'), nullable=False),
    sa.Column('redis_host', sa.String(), nullable=True),
    sa.Column('redis_queue_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('functions')
    # ### end Alembic commands ###
