services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      # Test to check if the database is ready for connections.
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    build: .
    # The command is now handled by the Dockerfile's ENTRYPOINT and CMD.
    # We don't need to specify it here.
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      # Pass the database credentials from the .env file to the container.
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      POSTGRES_SERVER: db # The service name 'db' is the hostname inside the Docker network.
      POSTGRES_PORT: 5432
    depends_on:
      db:
        condition: service_healthy # This condition waits for the healthcheck to pass.

volumes:
  postgres_data:
